# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(1129, 738)
        Menu.setStyleSheet("background:rgb(30,30,30);\n"
"color:white;\n"
"")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Menu)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Menu)
        self.tabWidget.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background:rgb(30,30,30);\n"
"color:black;\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Button_Upload_Original = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Upload_Original.setFont(font)
        self.Button_Upload_Original.setStyleSheet("background:white;\n"
"")
        self.Button_Upload_Original.setObjectName("Button_Upload_Original")
        self.verticalLayout_2.addWidget(self.Button_Upload_Original)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_17 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:white;")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.radioButton_AES = QtWidgets.QRadioButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_AES.setFont(font)
        self.radioButton_AES.setStyleSheet("color: white;")
        self.radioButton_AES.setObjectName("radioButton_AES")
        self.horizontalLayout_9.addWidget(self.radioButton_AES)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.radioButton_Blowfish = QtWidgets.QRadioButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_Blowfish.setFont(font)
        self.radioButton_Blowfish.setStyleSheet("color: white;")
        self.radioButton_Blowfish.setObjectName("radioButton_Blowfish")
        self.horizontalLayout_9.addWidget(self.radioButton_Blowfish)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.Button_Encrypt = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Encrypt.setFont(font)
        self.Button_Encrypt.setStyleSheet("background:red;\n"
"color:white;")
        self.Button_Encrypt.setObjectName("Button_Encrypt")
        self.verticalLayout_2.addWidget(self.Button_Encrypt)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_key_tittle = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_key_tittle.setFont(font)
        self.label_key_tittle.setStyleSheet("color:white;")
        self.label_key_tittle.setObjectName("label_key_tittle")
        self.verticalLayout_2.addWidget(self.label_key_tittle)
        self.label_KEY = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_KEY.setFont(font)
        self.label_KEY.setStyleSheet("color:white;")
        self.label_KEY.setObjectName("label_KEY")
        self.verticalLayout_2.addWidget(self.label_KEY)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.Button_CreateWAV_Encrypt = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Button_CreateWAV_Encrypt.setFont(font)
        self.Button_CreateWAV_Encrypt.setStyleSheet("background:white;\n"
"")
        self.Button_CreateWAV_Encrypt.setObjectName("Button_CreateWAV_Encrypt")
        self.verticalLayout_2.addWidget(self.Button_CreateWAV_Encrypt)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:white;")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.MplWidget = MplWidget(self.tab)
        self.MplWidget.setStyleSheet("background:blue;")
        self.MplWidget.setObjectName("MplWidget")
        self.verticalLayout_13.addWidget(self.MplWidget)
        self.verticalLayout_9.addLayout(self.verticalLayout_13)
        self.Toolbar1 = QtWidgets.QVBoxLayout()
        self.Toolbar1.setObjectName("Toolbar1")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Toolbar1.addItem(spacerItem8)
        self.verticalLayout_9.addLayout(self.Toolbar1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider_Original = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_Original.setStyleSheet("QSlider::groove:horizontal{\n"
"    border: 1px solid black;\n"
"    height: 5px;\n"
"    background: white;\n"
"}\n"
"\n"
"QSlider::handle:horizontal{\n"
"    background: white;\n"
"    border: 1px solid black;\n"
"    width: 8px;\n"
"    margin: -3px 0;\n"
"    boder-radius: 9px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal{\n"
"    background-color: black;\n"
"}")
        self.horizontalSlider_Original.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Original.setObjectName("horizontalSlider_Original")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_Original)
        self.label_3 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(50, 50))
        self.label_3.setStyleSheet("image: url(:/notes/notes50x50.png);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/nota/notes50x50.png"))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem9)
        self.pushButton_play_O = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.pushButton_play_O.sizePolicy().hasHeightForWidth())
        self.pushButton_play_O.setSizePolicy(sizePolicy)
        self.pushButton_play_O.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_play_O.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_play_O.setFont(font)
        self.pushButton_play_O.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_play_O.setStyleSheet("QPushButton{\n"
"    border-image: url(:/play/play.png);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: black;\n"
"}")
        self.pushButton_play_O.setText("")
        self.pushButton_play_O.setObjectName("pushButton_play_O")
        self.horizontalLayout_15.addWidget(self.pushButton_play_O)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_15.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.pushButton_pausa_O = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.pushButton_pausa_O.sizePolicy().hasHeightForWidth())
        self.pushButton_pausa_O.setSizePolicy(sizePolicy)
        self.pushButton_pausa_O.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_pausa_O.setFont(font)
        self.pushButton_pausa_O.setStyleSheet("QPushButton{\n"
"    border-image: url(:/pausa/pause.png);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: black;\n"
"}")
        self.pushButton_pausa_O.setText("")
        self.pushButton_pausa_O.setObjectName("pushButton_pausa_O")
        self.horizontalLayout_15.addWidget(self.pushButton_pausa_O)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_15.addItem(spacerItem13)
        self.pushButton_rec_O = QtWidgets.QPushButton(self.tab)
        self.pushButton_rec_O.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_rec_O.setFont(font)
        self.pushButton_rec_O.setStyleSheet("QPushButton{\n"
"    border-image: url(:/stop/stop.png);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: black;\n"
"}")
        self.pushButton_rec_O.setText("")
        self.pushButton_rec_O.setObjectName("pushButton_rec_O")
        self.horizontalLayout_15.addWidget(self.pushButton_rec_O)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.verticalLayout_16.addLayout(self.horizontalLayout_15)
        self.verticalLayout_9.addLayout(self.verticalLayout_16)
        self.label_16 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:white;")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_9.addWidget(self.label_16)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.MplWidget_2 = MplWidget(self.tab)
        self.MplWidget_2.setStyleSheet("background:blue;")
        self.MplWidget_2.setObjectName("MplWidget_2")
        self.verticalLayout_6.addWidget(self.MplWidget_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem15)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSlider_Encrypt = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_Encrypt.setStyleSheet("QSlider::groove:horizontal{\n"
"    border: 1px solid black;\n"
"    height: 5px;\n"
"    background: white;\n"
"}\n"
"\n"
"QSlider::handle:horizontal{\n"
"    background: white;\n"
"    border: 1px solid black;\n"
"    width: 8px;\n"
"    margin: -3px 0;\n"
"    boder-radius: 9px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal{\n"
"    background-color: black;\n"
"}")
        self.horizontalSlider_Encrypt.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Encrypt.setObjectName("horizontalSlider_Encrypt")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_Encrypt)
        self.label_4 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(50, 50))
        self.label_4.setStyleSheet("image: url(:/notes/notes50x50.png);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/nota/notes50x50.png"))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_17.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem16)
        self.pushButton_play_E = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.pushButton_play_E.sizePolicy().hasHeightForWidth())
        self.pushButton_play_E.setSizePolicy(sizePolicy)
        self.pushButton_play_E.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_play_E.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_play_E.setFont(font)
        self.pushButton_play_E.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_play_E.setStyleSheet("QPushButton{\n"
"    border-image: url(:/play/play.png);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: black;\n"
"}")
        self.pushButton_play_E.setText("")
        self.pushButton_play_E.setObjectName("pushButton_play_E")
        self.horizontalLayout_16.addWidget(self.pushButton_play_E)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_16.addItem(spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem18)
        self.pushButton_pausa_E = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.pushButton_pausa_E.sizePolicy().hasHeightForWidth())
        self.pushButton_pausa_E.setSizePolicy(sizePolicy)
        self.pushButton_pausa_E.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_pausa_E.setFont(font)
        self.pushButton_pausa_E.setStyleSheet("QPushButton{\n"
"    border-image: url(:/pausa/pause.png);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: black;\n"
"}")
        self.pushButton_pausa_E.setText("")
        self.pushButton_pausa_E.setObjectName("pushButton_pausa_E")
        self.horizontalLayout_16.addWidget(self.pushButton_pausa_E)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem19)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_16.addItem(spacerItem20)
        self.pushButton_rec_E = QtWidgets.QPushButton(self.tab)
        self.pushButton_rec_E.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_rec_E.setFont(font)
        self.pushButton_rec_E.setStyleSheet("QPushButton{\n"
"    border-image: url(:/stop/stop.png);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: black;\n"
"}")
        self.pushButton_rec_E.setText("")
        self.pushButton_rec_E.setObjectName("pushButton_rec_E")
        self.horizontalLayout_16.addWidget(self.pushButton_rec_E)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem21)
        self.verticalLayout_17.addLayout(self.horizontalLayout_16)
        self.verticalLayout_9.addLayout(self.verticalLayout_17)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Button_Upload_Encrypt = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Upload_Encrypt.setFont(font)
        self.Button_Upload_Encrypt.setStyleSheet("background:white;\n"
"")
        self.Button_Upload_Encrypt.setObjectName("Button_Upload_Encrypt")
        self.verticalLayout_3.addWidget(self.Button_Upload_Encrypt)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem22)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:white;")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_8.addWidget(self.label_21)
        self.lineEdit_key = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_key.setStyleSheet("color:white;")
        self.lineEdit_key.setObjectName("lineEdit_key")
        self.horizontalLayout_8.addWidget(self.lineEdit_key)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem23)
        self.Button_Desencrypt = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Desencrypt.setFont(font)
        self.Button_Desencrypt.setStyleSheet("background:green;\n"
"color:white;")
        self.Button_Desencrypt.setObjectName("Button_Desencrypt")
        self.verticalLayout_3.addWidget(self.Button_Desencrypt)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem24)
        self.Button_CreateWAV_Desencrypt = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Button_CreateWAV_Desencrypt.setFont(font)
        self.Button_CreateWAV_Desencrypt.setStyleSheet("background:white;\n"
"")
        self.Button_CreateWAV_Desencrypt.setObjectName("Button_CreateWAV_Desencrypt")
        self.verticalLayout_3.addWidget(self.Button_CreateWAV_Desencrypt)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem25)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:white;")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_11.addWidget(self.label_18)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.MplWidget_5 = MplWidget(self.tab_2)
        self.MplWidget_5.setStyleSheet("background:blue;")
        self.MplWidget_5.setObjectName("MplWidget_5")
        self.verticalLayout_15.addWidget(self.MplWidget_5)
        self.verticalLayout_11.addLayout(self.verticalLayout_15)
        self.Toolbar1_3 = QtWidgets.QVBoxLayout()
        self.Toolbar1_3.setObjectName("Toolbar1_3")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Toolbar1_3.addItem(spacerItem26)
        self.verticalLayout_11.addLayout(self.Toolbar1_3)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalSlider_Encrypt2 = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_Encrypt2.setStyleSheet("QSlider::groove:horizontal{\n"
"    border: 1px solid black;\n"
"    height: 5px;\n"
"    background: white;\n"
"}\n"
"\n"
"QSlider::handle:horizontal{\n"
"    background: white;\n"
"    border: 1px solid black;\n"
"    width: 8px;\n"
"    margin: -3px 0;\n"
"    boder-radius: 9px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal{\n"
"    background-color: black;\n"
"}")
        self.horizontalSlider_Encrypt2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Encrypt2.setObjectName("horizontalSlider_Encrypt2")
        self.horizontalLayout_10.addWidget(self.horizontalSlider_Encrypt2)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(50, 50))
        self.label_7.setStyleSheet("image: url(:/notes/notes50x50.png);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/nota/notes50x50.png"))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.verticalLayout_20.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem27)
        self.pushButton_play_E2 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.pushButton_play_E2.sizePolicy().hasHeightForWidth())
        self.pushButton_play_E2.setSizePolicy(sizePolicy)
        self.pushButton_play_E2.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_play_E2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_play_E2.setFont(font)
        self.pushButton_play_E2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_play_E2.setStyleSheet("QPushButton{\n"
"    border-image: url(:/play/play.png);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: black;\n"
"}")
        self.pushButton_play_E2.setText("")
        self.pushButton_play_E2.setObjectName("pushButton_play_E2")
        self.horizontalLayout_19.addWidget(self.pushButton_play_E2)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_19.addItem(spacerItem28)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem29)
        self.pushButton_pausa_E2 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.pushButton_pausa_E2.sizePolicy().hasHeightForWidth())
        self.pushButton_pausa_E2.setSizePolicy(sizePolicy)
        self.pushButton_pausa_E2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_pausa_E2.setFont(font)
        self.pushButton_pausa_E2.setStyleSheet("\n"
"QPushButton{\n"
"    border-image: url(:/pausa/pause.png);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: black;\n"
"}")
        self.pushButton_pausa_E2.setText("")
        self.pushButton_pausa_E2.setObjectName("pushButton_pausa_E2")
        self.horizontalLayout_19.addWidget(self.pushButton_pausa_E2)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem30)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_19.addItem(spacerItem31)
        self.pushButton_rec_E2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_rec_E2.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_rec_E2.setFont(font)
        self.pushButton_rec_E2.setStyleSheet("QPushButton{\n"
"    border-image: url(:/stop/stop.png);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: black;\n"
"}")
        self.pushButton_rec_E2.setText("")
        self.pushButton_rec_E2.setObjectName("pushButton_rec_E2")
        self.horizontalLayout_19.addWidget(self.pushButton_rec_E2)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem32)
        self.verticalLayout_20.addLayout(self.horizontalLayout_19)
        self.verticalLayout_11.addLayout(self.verticalLayout_20)
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:white;")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_11.addWidget(self.label_22)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.MplWidget_6 = MplWidget(self.tab_2)
        self.MplWidget_6.setStyleSheet("background:blue;")
        self.MplWidget_6.setObjectName("MplWidget_6")
        self.verticalLayout_8.addWidget(self.MplWidget_6)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_12.addItem(spacerItem33)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalSlider_Desencrypt = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_Desencrypt.setStyleSheet("QSlider::groove:horizontal{\n"
"    border: 1px solid black;\n"
"    height: 5px;\n"
"    background: white;\n"
"}\n"
"\n"
"QSlider::handle:horizontal{\n"
"    background: white;\n"
"    border: 1px solid black;\n"
"    width: 8px;\n"
"    margin: -3px 0;\n"
"    boder-radius: 9px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal{\n"
"    background-color: black;\n"
"}")
        self.horizontalSlider_Desencrypt.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Desencrypt.setObjectName("horizontalSlider_Desencrypt")
        self.horizontalLayout_11.addWidget(self.horizontalSlider_Desencrypt)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(50, 50))
        self.label_8.setStyleSheet("image: url(:/notes/notes50x50.png);")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/nota/notes50x50.png"))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.verticalLayout_21.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem34)
        self.pushButton_play_D = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.pushButton_play_D.sizePolicy().hasHeightForWidth())
        self.pushButton_play_D.setSizePolicy(sizePolicy)
        self.pushButton_play_D.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_play_D.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_play_D.setFont(font)
        self.pushButton_play_D.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_play_D.setStyleSheet("QPushButton{\n"
"    border-image: url(:/play/play.png);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: black;\n"
"}")
        self.pushButton_play_D.setText("")
        self.pushButton_play_D.setObjectName("pushButton_play_D")
        self.horizontalLayout_20.addWidget(self.pushButton_play_D)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_20.addItem(spacerItem35)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem36)
        self.pushButton_pausa_D = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.pushButton_pausa_D.sizePolicy().hasHeightForWidth())
        self.pushButton_pausa_D.setSizePolicy(sizePolicy)
        self.pushButton_pausa_D.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_pausa_D.setFont(font)
        self.pushButton_pausa_D.setStyleSheet("QPushButton{\n"
"    border-image: url(:/pausa/pause.png);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: black;\n"
"}")
        self.pushButton_pausa_D.setText("")
        self.pushButton_pausa_D.setObjectName("pushButton_pausa_D")
        self.horizontalLayout_20.addWidget(self.pushButton_pausa_D)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem37)
        spacerItem38 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_20.addItem(spacerItem38)
        self.pushButton_rec_D = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_rec_D.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_rec_D.setFont(font)
        self.pushButton_rec_D.setStyleSheet("QPushButton{\n"
"    border-image: url(:/stop/stop.png);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: black;\n"
"}")
        self.pushButton_rec_D.setText("")
        self.pushButton_rec_D.setObjectName("pushButton_rec_D")
        self.horizontalLayout_20.addWidget(self.pushButton_rec_D)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem39)
        self.verticalLayout_21.addLayout(self.horizontalLayout_20)
        self.verticalLayout_11.addLayout(self.verticalLayout_21)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_7.addLayout(self.verticalLayout)

        self.retranslateUi(Menu)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Form"))
        self.tabWidget.setToolTip(_translate("Menu", "<html><head/><body><p><br/></p></body></html>"))
        self.Button_Upload_Original.setText(_translate("Menu", "UPLOAD"))
        self.label_17.setText(_translate("Menu", "ALGORITHM:"))
        self.radioButton_AES.setText(_translate("Menu", "AES"))
        self.radioButton_Blowfish.setText(_translate("Menu", "BLOWFISH"))
        self.Button_Encrypt.setText(_translate("Menu", "ENCRYPT"))
        self.label_key_tittle.setText(_translate("Menu", "KEY:"))
        self.label_KEY.setText(_translate("Menu", "Text"))
        self.Button_CreateWAV_Encrypt.setText(_translate("Menu", "CREATE .WAV"))
        self.label_15.setText(_translate("Menu", "ORIGINAL FFT:"))
        self.label_16.setText(_translate("Menu", "ENCRYPT FFT:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Menu", "Encriptador"))
        self.Button_Upload_Encrypt.setText(_translate("Menu", "UPLOAD"))
        self.label_21.setText(_translate("Menu", "KEY:"))
        self.Button_Desencrypt.setText(_translate("Menu", "DESENCRYPT"))
        self.Button_CreateWAV_Desencrypt.setText(_translate("Menu", "CREATE .WAV"))
        self.label_18.setText(_translate("Menu", "ENCRYPT FFT:"))
        self.label_22.setText(_translate("Menu", "DESENCRYPT FFT:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Menu", "Desencriptador"))

from Frontend.src.mplwidget import *

import Frontend.src.ui.notes50x50
import Frontend.src.ui.play
import Frontend.src.ui.pause
import Frontend.src.ui.stop


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QWidget()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())
